<?php

namespace OC\WestoryBundle\Manager;

use Doctrine\ORM\EntityManager;

/**
 * StoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StoryManager {

	protected $em;

	public function __construct(EntityManager $em){
		$this->em = $em;
	}

	public function addAuthor($story, $user){
		$story->setAuthor($user->getUsername());
		$this->em->persist($story);
		$this->em->flush();
	}
      		

}
