<?php

namespace OC\WestoryBundle\Repository;

use Doctrine\ORM\QueryBuilder;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends \Doctrine\ORM\EntityRepository{

	public function insertComment($comment, $story, $user){
		$comment->setAuthor($user->getUsername());
		$comment->setStory($story);
		$this->getEntityManager()->persist($comment);
		$this->getEntityManager()->flush();
	}

	public function getComments($pageCom, $comPerPage, $story){
		$query = $this->createQueryBuilder('c')
			->where('c.story = :story')
			->setParameter('story', $story)
		    ->getQuery()
    	;

		$query
	      ->setFirstResult(($pageCom-1) * $comPerPage)
	      ->setMaxResults($comPerPage)
	    ;
	    return new Paginator($query, true);
	}

}
