<?php

namespace OC\WestoryBundle\Repository;

/**
 * MembersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MembersRepository extends \Doctrine\ORM\EntityRepository{

	public function getUserValid($user, $email){
		$query = $this->createQueryBuilder('a')
			->where('a.username = :user')
			->setParameter('user', $user)
			->andWhere('a.emailAddress = :email')
			->setParameter('email', $email)
			;

		return $query
			->getQuery()
			->getOneOrNullResult()
			;
	}

}
